### PR TITLE
enhancement: update report UI, show more test details

### PR DESCRIPTION
**Pull request by kien-ht**
#### This PR aims to provide a better UI for our report:
- “Treeify” test results to reflect the specs directory
- Show essential stats: total snapshots, fails, passes, percentage, failure threshold
- Filter tests by status: all/pass/fail
- Expand all/Collapse all tests
- View snapshots in modal mode, can easily slide between: baseline/diff/comparison. Arrow left and right keypress events are also supported

Note: Bootstrap was totally removed as I came to realize we don't actually need it. It might save us some kilobytes

### CODE REVIEW

**Comment by PippoRaimondi** [comment]
this is pretty cool! I will test locally and merge/approve shortly!

**Comment by kien-ht** [comment]
By the way, as I was working with our report tree, I found out that there's a limitation with our current snapshot naming convention. In cases where I have multiple snapshots in one single test file, and I want them to all sit inside a folder named by its test file instead of having them scattered in `baseline` (or `diff`, or `comparison`). I could possibly give each snapshot name a prefix "/", just like in a regular cypress snapshot command.
For example, if I have this structure:

```
|-- spec
  |--my-test-spec.js
```

```
// my-test-spec.js
...
cy.compareSnapshot('/home-page')
```

I would expect to see the generated `baseline` folder to be as followed:
```
|-- baseline
  |--my-test-spec
    |--home-page.png

```
But the actual result is:
```
|-- baseline
  |--my-test-spec-
    |--home-page.png
```

Notice there is an unexpected "-" at the end of `my-test-spec` folder name, which looks a bit weird. I'd like to take a shot to fix that in my next PR if you think that it's reasonable.

I believe being able to group snapshots from within a test file in the same folder makes our report looking neat and organized.

**Comment by PippoRaimondiDIT** [comment]
> By the way, as I was working with our report tree, I found out that there's a limitation with our current snapshot naming convention. In case where I have multiple snapshots in one single test file, and I want them to sit all inside a folder named by its test file instead of having them scattered in `baseline` (or `diff`, or `comparison`). I could possibly give each snapshot name a prefix "/", just like in a regular cypress snapshot command. For example, if I have this structure:
> 
> ```
> |-- spec
>   |-- my-test-spec.js
> ```
> 
> ```
> // my-test-spec.js
> ...
> cy.compareSnapshot('/home-page')
> ```
> 
> I would expect to see the generated `baseline` folder to be as followed:
> 
> ```
> |-- baseline
>   |-- my-test-spec
>     |-- home-page.png
> ```
> 
> But the actual result is:
> 
> ```
> |-- baseline
>   |-- my-test-spec-
>     |-- home-page.png
> ```
> 
> Notice there is an unexpected "-" at the end of `my-test-spec` folder name, which looks a bit weird. I'd like to take a shot to fix that in my next PR if you think that it's reasonable.
> 
> I believe being able to group snapshots from within a test file in the same folder makes our report looking neat and organized.

Agreed! I haven't had a lot of time to sort this things out during this summer, I appreciate you helping out! I am testing this change locally now and will merge today if all good... 

I will open an issue with your finding above, so it could be tracked and eventually fixed!

**Comment by PippoRaimondiDIT** [comment]
Just tested it locally, report looks amazing!! good job man!

**Pull request merged**
