### PR TITLE
add babel runtime as a dependencies, optimize for complex folder structure

### PR DESCRIPTION
**Pull request by ssddi456**

### CODE REVIEW

**Review by PippoRaimondi — CHANGES_REQUESTED** [review]
I need to write a checklist for contributors, meanwhile can you at least provide the following:

- Reason of the change in the description
- Add unit tests if possible, if not confirm the feature is covered by the e2e test (it seems if we add a e2e test with a complex folder structure should be enough to validate the changes)
- In order to trigger a new version/release your commit message (at least one of the commits) needs to follow a particular pattern. for example for a new feature right: `feature: optimise for complex file structure`

**Comment by ssddi456** [comment]
ok, i'll add test later

**Comment by mehrad-rafigh** [comment]
@ssddi456 Any update on your PR? Can you finalize it?

**Comment by PippoRaimondi** [comment]
> @ssddi456 Any update on your PR? Can you finalize it?

I will finalise it now!

**Comment by PippoRaimondi** [comment]
I am accepting this PR and will add a test in a separate one.. I've validated the change and it looks good!

**Pull request merged**
