### PR TITLE
Fix: undefined files

### PR DESCRIPTION
**Pull request by narinluangrath**
When a Cypress test fails, it will automatically generate a screenshot of the test runner with a file path like `"cypress/screenshots/<spec_file>/<test_name> (failed).png"`. `cypress-image-diff` should not touch these screenshots (i.e. don't copy them over to `cypress-visual-screenshots`) because they are unrelated to this plugin.

Fortunately, it's easy to filter for these screenshots in the `after:screenshot` event because they have a property `testFailure: true`, e.g.

```js
on('after:screenshot', details => {

console.log(details);

// {
//   testAttemptIndex: 0,
//   size: 45868,
//   takenAt: '2022-01-03T00:02:24.148Z',
//   dimensions: { width: 1280, height: 720 },
//   multipart: false,
//   specName: 'image-diff-spec.js',
//   testFailure: true, 
//   path: '/code/cypress/screenshots/image-diff-spec.js/Visuals -- should compare screenshot of the entire page (failed).png',
//   scaled: true,
//   blackout: [],
//   duration: 120
// }

}

### CODE REVIEW

**Comment by PippoRaimondi** [comment]
Let me have a think about this... the only problem I can see is that if people use this plugin alongside with their other test suite setup, it would stop generating failed screenshots for normal tests

**Comment by deivydasp** [comment]
I think the author of PR have in mind that cypress-image-diff copies failing screenshot into cypress-visual-screenshots->comparison with "undefined.png" name.
image
paramter is set:
"env": {
    "preserveOriginalScreenshot": true
  }

**Comment by pjanaya** [comment]
I have tried using `"preserveOriginalScreenshot": true` but the result is the same. The screenshot for the failed test is moved to the cypress-visual-screenshots folder as undefined.png. This is breaking our integration with Cypress Dashboard.

What is preventing this PR from being merged? It seems perfectly valid 😕 If you have concerns about this @PippoRaimondi, we could hide this behind a flag on Cypress.json. Therefore, only those who really need it (like us) can use it and nothing will break for anyone else.

**Comment by DavicVictor** [comment]
Hello ! Can we please do something to merge this PR, it is breaking my cypress dashboard as well. Have you guys found a workaround do it without having to merge this PR ?

**Comment by PippoRaimondi** [comment]
Took me a while to thoroughly test this. I am finally merging, apologies for the delay @DavicVictor & @pjanaya ...

Thanks a lot for the contribution @narinluangrath

**Comment by PippoRaimondi** [comment]
actually, @narinluangrath can you please rebase? if not I would need to create a new PR so it triggers the pipeline...

**Comment by narinluangrath** [comment]
> actually, @narinluangrath can you please rebase? if not I would need to create a new PR so it triggers the pipeline...

Will do after I'm off working hours (5pm PST)!

**Comment by narinluangrath** [comment]
@PippoRaimondi I accidentally merged instead of rebasing. Looks like it triggered the pipeline. Let me know if you really need a rebase.

**Pull request merged**
